/**
 * VantaOS custom Cloudflare Worker entry point.
 *
 * Intercepts GET /api/model-proxy and handles it natively at the workerd
 * layer (CPU-exempt zero-copy body passthrough) so large `.onnx_data` weight
 * shards (>500MB) stream without burning the OpenNext Node.js runtime's CPU
 * budget. Everything else is delegated 1:1 to the OpenNext-generated worker.
 *
 * See https://opennext.js.org/cloudflare/howtos/custom-worker
 */
import { handleModelProxyGet } from './src/lib/server/model-proxy';
// @ts-ignore -- generated by `npx opennextjs-cloudflare build`
import { default as opennextWorker } from './.open-next/worker.js';

const MODEL_PROXY_PATH = '/api/model-proxy';

export default {
  async fetch(request: Request, env: any, ctx: any): Promise<Response> {
    const url = new URL(request.url);
    if (request.method === 'GET' && url.pathname === MODEL_PROXY_PATH) {
      return handleModelProxyGet(request);
    }
    return opennextWorker.fetch(request, env, ctx);
  },
} as const;