import { Shield, CheckCircle, Lock, Eye, Database } from 'lucide-react';
import React from 'react';

export default function PrivacyPolicy() {
  return (
    <div className="flex flex-col gap-10 w-full max-w-4xl mx-auto animate-in fade-in duration-500 pb-12">
      <div className="flex flex-col items-center text-center gap-6 py-12 border-b border-white/10">
        <div className="inline-flex items-center gap-2 px-4 py-1.5 bg-indigo-500/10 border border-indigo-500/30 rounded-full shadow-sm">
          <Shield className="w-4 h-4 text-indigo-400" />
          <span className="text-xs uppercase tracking-widest font-bold text-indigo-300">VantaOS Trust Center</span>
        </div>

        <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight text-white drop-shadow-sm">
          Data Privacy & Ownership
        </h1>
        <p className="text-slate-400 text-lg max-w-2xl mx-auto">
          At VantaOS, we believe your data belongs to you. Our architecture ensures absolute data sovereignty,
          transparent model training, and zero-trust execution.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        <div className="bg-white/5 rounded-2xl border border-white/10 p-8 flex flex-col gap-6 hover:border-indigo-500/30 transition-colors">
          <div className="w-14 h-14 bg-indigo-500/10 rounded-2xl flex items-center justify-center">
            <Lock className="w-7 h-7 text-indigo-400" />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-white mb-3 tracking-tight">1. Absolute Data Sovereignty</h2>
            <p className="text-slate-400 leading-relaxed">
              You retain 100% ownership of your data and runtime configurations. Your interactions with
              the platform are secured in transit via standard TLS encryption, and data stored in our
              database is protected using robust Row Level Security (RLS) policies in Supabase. This
              ensures that your private data is strictly accessible only to your authenticated user session.
            </p>
          </div>
        </div>

        <div className="bg-white/5 rounded-2xl border border-white/10 p-8 flex flex-col gap-6 hover:border-emerald-500/30 transition-colors">
          <div className="w-14 h-14 bg-emerald-500/10 rounded-2xl flex items-center justify-center">
            <Eye className="w-7 h-7 text-emerald-400" />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-white mb-3 tracking-tight">2. Transparent Model Training</h2>
            <p className="text-slate-400 leading-relaxed">
              We enforce full transparency in all data-handling processes. No proprietary data is ever
              used to fine-tune our global AI assistants without explicit opt-in. All model architectures
              generated by the Technical Co-Pilot are completely open-source and yours to modify.
            </p>
          </div>
        </div>

        <div className="bg-white/5 rounded-2xl border border-white/10 p-8 flex flex-col gap-6 hover:border-purple-500/30 transition-colors">
          <div className="w-14 h-14 bg-purple-500/10 rounded-2xl flex items-center justify-center">
            <CheckCircle className="w-7 h-7 text-purple-400" />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-white mb-3 tracking-tight">3. Zero-Cost, Zero-Tracking</h2>
            <p className="text-slate-400 leading-relaxed">
              The VantaOS ecosystem operates under a strict $0 cost mandate. Because we do not rely on
              paywalls, commercial tiers, or data brokering, there are no hidden tracking scripts, no
              advertising SDKs, and no telemetry data sold to third parties. Our Autonomous Threat
              Neutralization Watchdog protects your node without logging your personal IP data.
            </p>
          </div>
        </div>
      </div>

      <div className="bg-white/5 rounded-2xl border border-white/10 p-8 text-center mt-6">
        <p className="text-slate-400 text-sm leading-relaxed">
          Engineered with precision for the open-source community.
        </p>
        <p className="text-slate-500 text-xs mt-2">
          Built by the VantaOS team — open-source and privacy-first.
        </p>
      </div>
    </div>
  );
}
